spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://{EndPoint}:{Port}/{DB_name}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: {DB_username}
    password: {DB_password}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

logging:
  level:
    '[org.springframework.boot.web]': INFO